//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "spendings", table_name = "spendings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: uuid::Uuid,
    pub user_id: uuid::Uuid,
    #[sea_orm(column_name = "date")]
    pub spending_date: Option<time::Date>,
    #[sea_orm(column_type = "Text", column_name = "type")]
    pub spending_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub amount: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
