DB_SCHEMA = "spendings"
DB_USER = "grosh"
DB_PASSWORD = "grosh"
DB_URL = "postgres://$(DB_USER):$(DB_PASSWORD)@127.0.0.1/groshekeli"
BIND_ADDRESS = "0.0.0.0:58888"

run:
	GROSH_DB_URL=$(DB_URL) GROSH_SPENDINGS_SCHEMA=$(DB_SCHEMA) GROSH_SPENDINGS_BIND_ADDRESS=$(BIND_ADDRESS) cargo run

migrate:
	@echo 'CREATE SCHEMA IF NOT EXISTS spendings' | psql $(DB_URL)
	GROSH_DB_URL=$(DB_URL) GROSH_SPENDINGS_SCHEMA=$(DB_SCHEMA) GROSH_SPENDINGS_BIND_ADDRESS=$(BIND_ADDRESS) cargo run -- -migrate up
